name: reflect_innovation
description: Reflect Innovation Cross-Platform App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.21.0+1
  shared_preferences:
  synchronized:
  flutter_bloc: ^7.0.0
  rxdart: ^0.23.1
  fluttertoast: ^6.0.0
  http: ^0.13.0
  dio: ^4.0.0
  permission_handler: ^4.2.0+hotfix.3
  fimber: ^0.1.10
  flutter_ble_lib:
  flutter_keyboard_size: ^1.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - asset/
    - asset/font/
    - asset/image/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: asset/font/ProximaNova-ExtraBold.ttf
          weight: 900
        - asset: asset/font/ProximaNova-Bold.ttf
          weight: 800
        - asset: asset/font/ProximaNova-SemiBold.ttf
          weight: 700
        - asset: asset/font/ProximaNova-Medium.ttf
          weight: 500
        - asset: asset/font/ProximaNova-Light.ttf
          weight: 400
        - asset: asset/font/ProximaNova-ExtraLight.ttf
          weight: 300
        - asset: asset/font/ProximaNova-Thin.ttf
          weight: 200

    - family: LibreBaskervilleBold
      fonts:
        - asset: asset/font/LibreBaskerville-Bold.ttf

    - family: LibreBaskervilleItalic
      fonts:
        - asset: asset/font/LibreBaskerville-Italic.ttf

    - family: LibreBaskervilleRegular
      fonts:
        - asset: asset/font/LibreBaskerville-Regular.ttf
